global:
  host: "loadtesting.xix.in"
  database:
    host: "192.168.56.13"
    user: "postgres"
    port: "5432"
    vendor: "postgres"
  registry:
    database: "registry"
    search_provider: "dev.sunbirdrc.registry.service.ElasticSearchService"
    sso:
      realm: "sunbird-rc"
      admin_client_id: "admin-api"
      client_id: "registry-frontend"
    signature_enabled: true
    keycloak_user_set_password: false
    base_apis_enabled: false
    log_level: INFO
    enable_external_templates: true
    enable_async: false
    enable_authentication: true
    enable_webhook: false
    webhook_url: http://localhost:5001/api/v1/callback
    manager_type: DefinitionsManager
  elastic_search:
    url: 10.9.0.9:9200
    auth_enabled: false
    username: ""
  kafka:
    url:
  secrets:
    DB_PASSWORD: cG9zdGdyZXMtcGFzcw==
    ELASTIC_SEARCH_PASSWORD: ""
    MINIO_SECRET_KEY: Kgo=
