global:
  host: "192.168.56.14"
  database:
    host: "192.168.56.13"
    user: "postgres"
    port: "5432"
    vendor: "postgres"
  registry:
    database: "registry"
    search_provider: "dev.sunbirdrc.registry.service.NativeSearchService"
    sso:
      realm: "sunbird-rc"
      admin_client_id: "admin-api"
      client_id: "registry-frontend"
    signature_enabled: true
    keycloak_user_set_password: false
    base_apis_enabled: false
    log_level: INFO
    enable_external_templates: true
    enable_async: false
    enable_authentication: false
    enable_webhook: false
    webhook_url: http://localhost:5001/api/v1/callback
    manager_type: DefinitionsManager
    swagger_enabled: true
    swagger_title: SUNBIRD-RC
    authentication_enabled: true
    claims_enabled: false
    certificate_enabled: false
    encryption_enabled: false
    opa_enabled: false
    opa_allow_key_name: authorized
  elastic_search:
    url: 192.168.56.18:9200
    auth_enabled: false
    username: ""
  kafka:
    url: 192.168.56.17
  secrets:
    DB_PASSWORD: cG9zdGdyZXMtcGFzcw==
