apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DB_ADDR: {{.Values.global.database.host | quote}}
  DB_DATABASE: {{.Values.global.keycloak.database | quote}}
  DB_PORT: {{.Values.global.database.port | quote}}
  DB_USER: {{.Values.global.database.user | quote}}
  DB_VENDOR: {{.Values.global.database.vendor | quote}}
  KEYCLOAK_USER: {{.Values.global.keycloak.admin.username | quote}}
  PROXY_ADDRESS_FORWARDING: {{.Values.global.keycloak.proxy_forwarding | quote}}
  DATABASE_CONNECTION_INFO_0_URI: jdbc:postgresql://{{.Values.global.database.host}}:{{.Values.global.database.port}}/{{.Values.global.registry.database}}
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{.Values.global.database.host}}:{{.Values.global.database.port}}/{{.Values.global.registry.database}}
  DATABASE_CONNECTION_INFO_0_USERNAME: {{.Values.global.database.user | quote}}
  SPRING_DATASOURCE_USERNAME: {{.Values.global.database.user | quote}}
  ELASTIC_SEARCH_CONNECTION_URL: {{.Values.global.elastic_search.url | quote}}
  ELASTIC_SEARCH_AUTH_ENABLED: {{.Values.global.elastic_search.auth_enabled | quote}}
  ELASTIC_SEARCH_USERNAME: {{.Values.global.elastic_search.username | quote}}
  SEARCH_PROVIDER_NAME: {{.Values.global.registry.search_provider | quote}}
  IDENTITY_REALM: {{.Values.global.registry.sso.realm | quote}}
  IDENTITY_URL: http://{{ .Release.Name }}-keycloak-service:8080/auth
  IDENTITY_ADMIN_CLIENT_ID: {{.Values.global.registry.sso.admin_client_id | quote}}
  sunbird_sso_client_id: {{.Values.global.registry.sso.client_id | quote}}
  OAUTH2_RESOURCES_0_URI: http://{{ .Release.Name }}-keycloak-service:8080/auth/realms/sunbird-rc
  IDGEN_HEALTH_CHECK_URL: http://{{ .Release.Name }}-id-gen-service:8088/health
  IDGEN_GENERATE_URL: http://{{ .Release.Name }}-id-gen-service:8088/id/_generate
  IDGEN_ID_FORMAT_URL: http://{{ .Release.Name }}-id-gen-service:8088/id/_format/add
  ENCRYPTION_HEALTH_CHECK_URL: http://{{ .Release.Name }}-encryption-service:8013/health
  ENCRYPTION_URL: http://{{ .Release.Name }}-encryption-service:8013/crypto/v1/_encrypt
  ENCRYPTION_BATCH_URL: http://{{ .Release.Name }}-encryption-service:8013/crypto/v1/_encrypt
  DECRYPTION_URL: http://{{ .Release.Name }}-encryption-service:8013/crypto/v1/_decrypt
  DECRYPTION_BATCH_URL: http://{{ .Release.Name }}-encryption-service:8013/crypto/v1/_decrypt
  CLAIMS_URL: http://{{ .Release.Name }}-claim-ms:8082
  SIGNATURE_V1_SIGN_URL: http://{{ .Release.Name }}-certificate-signer:8079/sign
  SIGNATURE_V1_VERIFY_URL: http://{{ .Release.Name }}-certificate-signer:8079/verify
  SIGNATURE_V1_HEALTH_CHECK_URL: http://{{ .Release.Name }}-certificate-signer:8079/health
  SIGNATURE_ENABLED: {{.Values.global.registry.signature_enabled | quote}}
  CERTIFICATE_PDF_URL: http://{{ .Release.Name }}-certificate-api:8078/api/v1/certificatePDF
  CERTIFICATE_HEALTH_CHECK_URL=: http://{{ .Release.Name }}-certificate-api:8078/health
  TEMPLATE_BASE_URL: http://{{ .Release.Name }}-registry:8081/api/v1/templates/ #Looks for certificate templates for pdf copy of the signed certificate
  IDENTITY_DEFAULT_PASSWORD: {{.Values.global.registry.keycloak_user_set_password | quote}}
  FILE_STORAGE_ENABLED: {{.Values.global.registry.filestorage_enabled | quote}}
  FILE_STORAGE_CONNECTION_URL: {{.Values.global.minio.url | quote}}
  FILE_STORAGE_ACCESS_KEY: {{.Values.global.minio.access_key | quote}}
  FILE_STORAGE_BUCKET_NAME: {{.Values.global.minio.bucket_key | quote}}
  REGISTRY_BASE_APIS_ENABLED: {{.Values.global.registry.base_apis_enabled | quote}}
  LOGGING_LEVEL_ROOT: {{.Values.global.registry.log_level | quote}}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: {{.Values.global.registry.log_level | quote}}
  TEMPLATE_EXTERNAL_ENABLED: {{.Values.global.registry.enable_external_templates | quote}}
  ASYNC_ENABLED: {{.Values.global.registry.enable_async | quote}}
  AUTHENTICATION_ENABLED: {{.Values.global.registry.enable_authentication | quote}}
  KAFKA_BOOTSTRAP_ADDRESS : {{.Values.global.kafka.url | quote}}
  WEBHOOK_ENABLED: {{.Values.global.registry.enable_webhook | quote}}
  WEBHOOK_URL: {{.Values.global.registry.webhook_url | quote}}
  REDIS_HOST: {{.Values.global.redis.host | quote}}
  REDIS_PORT: {{.Values.global.redis.port | quote}}
  DEFINITIONS_MANAGER_TYPE: {{.Values.global.registry.manager_type | quote}}
  REGISTRY_URL: http://{{ .Release.Name }}-registry:8081
  opa_allow_key_name: {{.Values.global.registry.opa_allow_key_name | quote}}
  opa_enabled: {{.Values.global.registry.opa_enabled | quote}}
  swagger_enabled: {{.Values.global.registry.swagger_enabled| quote}}
  SWAGGER_TITLE: {{.Values.global.registry.swagger_title| quote}}
  CLAIMS_ENABLED: {{.Values.global.registry.claims_enabled | quote}}
  CERTIFICATE_ENABLED: {{.Values.global.registry.certificate_enabled | quote}}
  ENCRYPTION_ENABLED: {{.Values.global.registry.encryption_enabled | quote}}
  IDGEN_ENABLED: {{.Values.global.registry.idgen_enabled | quote}}
  spring.datasource.username: {{.Values.global.database.user | quote}}
  IDENTITY_BASE_URL: http://{{ .Release.Name }}-identity-service:3332
  SCHEMA_BASE_URL: http://{{ .Release.Name }}-credential-schema-service:3333
  CREDENTIAL_SERVICE_BASE_URL: http://{{ .Release.Name }}-credentials-service:3000
  JWKS_URI: {{.Values.global.sunbird.jwks_uri | quote}}
  ENABLE_AUTH: {{.Values.global.sunbird.enable_auth | quote}}
  VAULT_ADDR: {{.Values.global.vault.address | quote}} 
  VAULT_TOKEN: {{.Values.global.vault.token | quote}}
  VAULT_BASE_URL: {{.Values.global.vault.base_url | quote}}
  VAULT_ROOT_PATH: {{.Values.global.vault.root_path | quote}}
  VAULT_TIMEOUT: {{.Values.global.vault.vault_timeout | quote}}
  VAULT_PROXY: {{.Values.global.vault.vault_proxy | quote}}
  SIGNING_ALGORITHM: {{.Values.global.sunbird.signing_algo | quote}}
  QR_TYPE : {{.Values.global.sunbird.qr_type | quote}}
  WEB_DID_BASE_URL : {{.Values.global.sunbird.web_did_base_url | quote}}
  DID_ENABLED:  {{.Values.global.registry.did_enabled | quote}}
  DID_HEALTH_CHECK_URL: http://{{ .Release.Name }}-identity-service:3332/health
  DID_GENERATE_URL: http://{{ .Release.Name }}-identity-service:3332/did/generate
  DID_RESOLVE_URL: http://{{ .Release.Name }}-identity-service:3332/did/resolve/{id}
  SIGNATURE_PROVIDER_NAME: {{.Values.global.registry.signature_provider | quote}}
  SIGNATURE_V2_CREDENTIAL_DID_METHOD: {{.Values.global.registry.credential_did_method | quote}}
  SIGNATURE_V2_ISSUER_DID_METHOD: {{.Values.global.registry.issuer_did_method | quote}}
  SIGNATURE_V2_SCHEMA_AUTHOR: {{.Values.global.registry.schema_author | quote}}
  SIGNATURE_V2_SCHEMA_AUTHOR_DID_METHOD: {{.Values.global.registry.schema_author_did_method | quote}}
  SIGNATURE_V2_HEALTH_CHECK_URL: http://{{ .Release.Name }}-credentials-service:3000/health
  SIGNATURE_V2_ISSUE_URL: http://{{ .Release.Name }}-credentials-service:3000/credentials/issue
  SIGNATURE_V2_GET_URL: http://{{ .Release.Name }}-credentials-service:3000/credentials/{id}
  SIGNATURE_V2_DELETE_URL: http://{{ .Release.Name }}-credentials-service:3000/credentials/{id}
  SIGNATURE_V2_VERIFY_URL: http://{{ .Release.Name }}-credentials-service:3000/credentials/{id}/verify
  SIGNATURE_V2_VERIFY_ANY_URL: http://{{ .Release.Name }}-credentials-service:3000/credentials/verify
  SIGNATURE_V2_REVOCATION_LIST_URL: http://{{ .Release.Name }}-credentials-service:3000/credentials/revocation-list?issuerId={issuerDid}&page={page}&limit={limit}
  SIGNATURE_V2_SCHEMA_HEALTH_CHECK_URL: http://{{ .Release.Name }}-credential-schema-service:3333/health
  SIGNATURE_V2_SCHEMA_CREATE_URL: http://{{ .Release.Name }}-credential-schema-service:3333/credential-schema
  SIGNATURE_V2_SCHEMA_UPDATE_URL: http://{{ .Release.Name }}-credential-schema-service:3333/credential-schema/{id}/{version}
  SIGNATURE_V2_SCHEMA_GET_BY_ID_AND_VERSION_URL: http://{{ .Release.Name }}-credential-schema-service:3333/credential-schema/{id}/{version}
  SIGNATURE_V2_SCHEMA_SEARCH_BY_TAGS_URL: http://{{ .Release.Name }}-credential-schema-service:3333/credential-schema?tags={tags}
